:imagesdir: ../../images/patterns/criacionais
:source-highlighter: highlightjs
:numbered:
:unsafe:
:icons: font

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Paciente Builder Automático com Biblioteca Lombok (https://kinolien.github.io/gitzip/?download=/manoelcampos/padroes-projetos/tree/master/criacionais/04-builder/paciente-builder-automatico-lombok[zip])

Mostra como usar a biblioteca http://projectlombok.org[Lombok] para gerar builders automáticos em tempo de compilação.
O Lombok intercepta o processo de compilação e alterar o bytecode das classes onde as anotações dele foram incluídas.
Assim, ele altera o arquivo .class e não gera qualquer arquivo .java como a biblioteca [Immutables](../paciente-builder-automatico-immutables).

No entanto, como o IDE analisa o código fonte e não encontrará nenhum arquivo Java com a Builder, 
ele não reconheceria tal classe que o Lombok gerou. Por isso, o uso do Lombok requer suporte do IDE,
que é feito pela instalação de uma extensão. No entanto, os IDEs e editores mais conhecidos como 
NetBeans, IntelliJ e VS Code já vem com tal extensão instalada por padrão nas versões atuais.



