:source-highlighter: highlightjs
:allow-uri-read:
:safe: unsafe
:numbered:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

:toc: left

= Padrões de Projeto em Java 
Prof. Manoel Campos da Silva Filho <https://about.me/manoelcampos>

ifdef::env-github[]

image:https://github.com/manoelcampos/padroes-projetos/workflows/asciidoctor-ghpages/badge.svg[GitHub Pages,link=http://manoelcampos.com/padroes-projetos/]

[IMPORTANT]
====
- Se você não pretende fazer alterações neste repositório, não faça fork. Se fizer, sempre que o projeto for atualizado, sua cópia vai ficar absoleta. Se você quer apenas baixar para navegar localmente, faça um clone no botão `Code` acima.
- Se você quer apenas salvar o projeto para consulta posterior, use o botão `Star` ⭐️ acima. Isto ainda ajuda a divulgar o material.
====
endif::[]

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:

NOTE: Os diagramas dos diferentes padrões estão todos disponíveis no arquivo link:diagramas.staruml.mdj[diagramas.staruml.mdj].
Utilize o http://staruml.io[StarUML 3+] para abrir o arquivo.
endif::[]

Uma apresentação sobre como chegamos aos padrões de projetos e a importância deles pode ser link:padroes-projetos.pptx[acessada aqui].

== Categorias de Padrões

- link:comportamentais[Padrões Comportamentais]
- link:criacionais[Padrões Criacionais]
- link:estruturais[Padrões Estruturais]

== Exercícios

Na página de cada padrão normalmente há alguns exercícios,
mas uma lista adicional está link:exercicios[disponível aqui].

== Material Complementar

Links para materais complementares estão disponíveis na https://github.com/manoelcampos/padroes-projetos/wiki[Wiki].
