:source-highlighter: highlightjs
:allow-uri-read:
:safe: unsafe
:numbered:

// :toc: left

= Padrões de Projeto em Java

ifdef::env-github[image:https://github.com/manoelcampos/padroes-projetos/workflows/asciidoctor-ghpages/badge.svg[GitHub Pages]]

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:

NOTE: Os diagramas dos diferentes padrões estão todos disponíveis no arquivo link:diagramas.staruml.mdj[diagramas.staruml.mdj].
Utilize o http://staruml.io[StarUML 3+] para abrir o arquivo.
endif::[]

Uma apresentação sobre como chegamos aos padrões de projetos e a importância deles pode ser link:padroes-projetos.pptx[acessada aqui].

== Categorias de Padrões

- link:comportamentais[Padrões Comportamentais]
- link:criacionais[Padrões Criacionais]
- link:estruturais[Padrões Estruturais]

== Exercícios

Na página de cada padrão normalmente há alguns exercícios,
mas uma lista adicional está link:exercicios[disponível aqui].

== Material Complementar

Links para materais complementares estão disponíveis na https://github.com/manoelcampos/padroes-projetos/wiki[Wiki].
