slides:
	@#Compila o README o formato de slides em HTML
	asciidoctor-revealjs slides.adoc && echo "Slides HTML gerados com sucesso"
	asciidoctor-revealjs slides-strategy-funcional.adoc && echo "Slides HTML Programação Funcional gerados com sucesso"

clean:
	@#Apaga os arquivos gerados pelos comandos acima
	rm -f slides.html slides-strategy-funcional.html
