:source-highlighter: highlightjs
:numbered:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Consumo de Serviços de CEP com Quarkus (link:https://kinolien.github.io/gitzip/?download=/manoelcampos/padroes-projetos/tree/master/estruturais/adapter/cep-service-adapter-automatico[zip])

Esta versão do projeto mostra que, em determinadas situações,
não precisamos de fato implementar um padrão.
A linguagem e ferramentas que utilizamos podem
já fornecer recursos que resolvem o problema,
com o mínimo de esforço.

O projeto usa a biblioteca Jackson para parse de JSON,
para fornecer tal recurso por meio da anotação `@JsonAlias` que é utilizada
para atributos da classe `Endereco` que tem nomes distintos em diferentes
serviços de CEP.

// Sem o quarkus, as dependências são jackson-annotations e jackson-databind

Este é um projeto Java EE que utiliza o framework https://quarkus.io[Quarkus] que torna o desenvolvimento de backends en Java
extremamente produtivo e eficiente, além de embutir um servidor de aplicação leve, tornando trivial a implantação da aplicação.
Para mais detalhes sobre o Quarkus, veja a página oficial acima e um
projeto de exemplo detalhada https://github.com/manoelcampos/sd-webservices/tree/master/4.5-ws-rest-quarkus-framework[aqui].

== Requisitos

- JDK 11
- Maven 3.8.1 ou superior

== Executar o Projeto

Você pode iniciar o servidor com sua aplicação de diferentes maneiras:

- Usando o script mvnw incluído durante a criação do projeto: `./mvnw compile quarkus:dev`.
- Ou simplesmente clicando no botão Play em IDEs como o NetBeans, pois foi incluído o plugin maven exec para executar o comando acima mais facilmente.

==== Atualizando o projeto sem reiniciar o servidor

Bem, atualizar o projeto no servidor em execução e ver as alterações que você fez na sua aplicação é realmente complicado com o Quarkus: você precisa apenas salvar o projeto e boom: normalmente em menos de 1 segundo a aplicação estará rodando com as novas alterações 😱🚀😁.

Não é à toa que o slogan do Quarkus é "Supersonic Subatomic Java".

==== Acessando a aplicação

Se você estiver habituado a usar servidores como o GlassFish no NetBeans,
sabe que ao clicar no botão Play, o projeto é compilado e executado,
abrindo o navegador automaticamente.
Usando o Quarkus isso não ocorrerá.
Você deve abrir o navegador você mesmo. Neste caso, a aplicação estará disponível
em http://localhost:8080.
Observe que não há um caminho adicional com o nome da aplicação no final da URL,
pois a aplicação executa na raiz do servidor.
