:source-highlighter: highlightjs
:numbered:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Leitura de Retornos de Boletos Bancários usando o padrão Template Method com Node.js

Implementa a leitura de arquivos de retorno de boletos bancários utilizando
o padrão Template Method, evitando a duplicação de código da versão
com o padrão Strategy.
Este é apenas um projeto de exemplo e inclui todas as classes em um único
arquivo apenas para facilitar a leitura.
                    
== Instalação no Linux

Para instalar as ferramentas acima em Linux baseados em Debian (como Ubuntu e derivados), 
basta abrir um terminal no diretório raiz do projeto e executar:

[source, bash]
----
make linux
----

No entanto, se ao executar o comando ocorrer erro indicando que o programa make não foi encontrado,
execute:

[source, bash]
----
sudo apt-get install make
----

== Executando a Aplicação

Para iniciar a aplicação, podemos executar:

[source, bash]
----
npm start
----

Como não há um frontend, todo o resultado é mostrado no terminal.