:source-highlighter: highlightjs

= Leitura de Retorno de Boletos Bancários usando Strategy Pattern e Java Reflection (link:https://kinolien.github.io/gitzip/?download=/manoelcampos/padroes-projetos/tree/master/comportamentais/01-strategy/retorno-boleto-reflection[zip])

Esta é uma versão diferente do projeto de leitura de arquivos de retorno de boletos bancários. Tal versão requer no mínimo o Java 9 para compilar e executar. O projeto está configurado para usar Java 11, mas pode-se alterar para qualquer versão a partir da 9. Ele aplica o recurso de https://www.devmedia.com.br/conhecendo-java-reflection/29148[Reflection do Java] para permitir usar um laço de repetição `for` para atribuir o valor de cada campo lido de um arquivo de retorno para o atributo correspondente em um objeto `Boleto`.

Tal versão usa recursos de métodos `default` (com implementação) do Java 8 e métodos privados do Java 9 em Interfaces. Além disso, o projeto usa recursos de programação funcional.

Usando este projeto, no lugar de escrever uma linha de código para cada campo que desejarmos pegar do arquivo e armazenar em um objeto `Boleto`, como abaixo:

[source,java]
----
boleto.setId(Integer.parseInt(vetor[0]));
boleto.setCodBanco(vetor[1]);
boleto.setDataVencimento(LocalDate.parse(vetor[2], FORMATO_DATA));
----

podemos usar um `for` semelhante ao seguinte:

```java
for (int i = 0; i < totalCampos; i++) {
    setCampoBoleto(i, boleto, vetor[i]);
}
```

== AVISO

Apesar desta facilitade, o código é muito mais complicado e confuso para quem não entende de __Reflection__.
O código do projeto anterior é claro e direto.
A versão aqui apresentada serve apenas como curiosidade. Em uma aplicação real, esta implementação não é nada aconselhável, pois é mais complexa e a execução usando __Reflection__ é mais lenta.
__Reflection__ é bastante usado em Java, mas quando não há uma maneira mais simples de resolver um problema.

Em linguagens dinâmicas como JavaScript, conseguiríamos usar um `for` para esta tarefa naturalmente, sem precisar recorrer a recursos avançados da linguagem e nem tornar o código mais complexo.

Então, o projeto serve apenas para mostrar alguns recursos avançados da linguagem Java,
sendo um ótimo material de estudos.
