:source-highlighter: highlightjs
:numbered:
:unsafe:
:icons: font

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Projeto Base que obtem a cotação de empresas da bolsa de valores (link:https://kinolien.github.io/gitzip/?download=/manoelcampos/padroes-projetos/tree/master/estruturais/adapter/cotacao-bolsa-valores[zip])

O projeto utiliza 3 serviços diferentes (Yahoo Finance, AlphaVantage e Quandl) para obter a cotação de empresas da bolsa de valores.
São utilizadas bibliotecas existentes para fazer acesso a estes serviços
e o código disponibilizado mostra como usar cada uma destas bibliotecas.

Mas como observará, a forma de utilizar cada uma é totalmente diferente da outra.
A partir deste código, altere o projeto criando 3 adaptadores: um pra cada uma
das bibliotecas dos serviços mencionados.
Com isto, será possível trocar um serviço pelo outro sem alterar o código do projeto.

Adicionalmente, você perceberá que o código das empresas tem formato diferente em cada serviço.
Como os adaptadores poderiam padronizar estes códigos e tornar o formato igual para todos os serviços?

No projeto disponibilizado, a classe `Principal` é na nossa classe `Cliente`: é ela quem usa os adaptadores. 
Analisando o novo código da classe principal, que outro padrão poderíamos aplicar em seguida?
